- id: "check_year"
  name: "Test Hook"
  entry: bash check-year.sh
  types: [text]
  exclude: ".yaml$|.yml$"
  language: "script"
  description: "Check that the license in LICENSE is valid for the current year."
